[][
	({ get [Symbol.toStringTag]() { return 'f' } }).toString().replace(/........(.)./, '$1')
	+ ({ get [Symbol.toStringTag]() { return 'i' } }).toString().replace(/........(.)./, '$1')
	+ ({ get [Symbol.toStringTag]() { return 'l' } }).toString().replace(/........(.)./, '$1')
	+ ({ get [Symbol.toStringTag]() { return 't' } }).toString().replace(/........(.)./, '$1')
	+ ({ get [Symbol.toStringTag]() { return 'e' } }).toString().replace(/........(.)./, '$1')
	+ ({ get [Symbol.toStringTag]() { return 'r' } }).toString().replace(/........(.)./, '$1')
][
	({ get [Symbol.toStringTag]() { return 'c' } }).toString().replace(/........(.)./, '$1')
	+ ({ get [Symbol.toStringTag]() { return 'o' } }).toString().replace(/........(.)./, '$1')
	+ ({ get [Symbol.toStringTag]() { return 'n' } }).toString().replace(/........(.)./, '$1')
	+ ({ get [Symbol.toStringTag]() { return 's' } }).toString().replace(/........(.)./, '$1')
	+ ({ get [Symbol.toStringTag]() { return 't' } }).toString().replace(/........(.)./, '$1')
	+ ({ get [Symbol.toStringTag]() { return 'r' } }).toString().replace(/........(.)./, '$1')
	+ ({ get [Symbol.toStringTag]() { return 'u' } }).toString().replace(/........(.)./, '$1')
	+ ({ get [Symbol.toStringTag]() { return 'c' } }).toString().replace(/........(.)./, '$1')
	+ ({ get [Symbol.toStringTag]() { return 't' } }).toString().replace(/........(.)./, '$1')
	+ ({ get [Symbol.toStringTag]() { return 'o' } }).toString().replace(/........(.)./, '$1')
	+ ({ get [Symbol.toStringTag]() { return 'r' } }).toString().replace(/........(.)./, '$1')
](
	({ get [Symbol.toStringTag]() { return 'r' } }).toString().replace(/........(.)./, '$1')
	+ ({ get [Symbol.toStringTag]() { return 'e' } }).toString().replace(/........(.)./, '$1')
	+ ({ get [Symbol.toStringTag]() { return 't' } }).toString().replace(/........(.)./, '$1')
	+ ({ get [Symbol.toStringTag]() { return 'u' } }).toString().replace(/........(.)./, '$1')
	+ ({ get [Symbol.toStringTag]() { return 'r' } }).toString().replace(/........(.)./, '$1')
	+ ({ get [Symbol.toStringTag]() { return 'n' } }).toString().replace(/........(.)./, '$1')
	+ ({ get [Symbol.toStringTag]() { return ' ' } }).toString().replace(/........(.)./, '$1')
	+ ({ get [Symbol.toStringTag]() { return 't' } }).toString().replace(/........(.)./, '$1')
	+ ({ get [Symbol.toStringTag]() { return 'h' } }).toString().replace(/........(.)./, '$1')
	+ ({ get [Symbol.toStringTag]() { return 'i' } }).toString().replace(/........(.)./, '$1')
	+ ({ get [Symbol.toStringTag]() { return 's' } }).toString().replace(/........(.)./, '$1')
)
()
[
	({ get [Symbol.toStringTag]() { return 'c' } }).toString().replace(/........(.)./, '$1')
	+ ({ get [Symbol.toStringTag]() { return 'o' } }).toString().replace(/........(.)./, '$1')
	+ ({ get [Symbol.toStringTag]() { return 'n' } }).toString().replace(/........(.)./, '$1')
	+ ({ get [Symbol.toStringTag]() { return 's' } }).toString().replace(/........(.)./, '$1')
	+ ({ get [Symbol.toStringTag]() { return 'o' } }).toString().replace(/........(.)./, '$1')
	+ ({ get [Symbol.toStringTag]() { return 'l' } }).toString().replace(/........(.)./, '$1')
	+ ({ get [Symbol.toStringTag]() { return 'e' } }).toString().replace(/........(.)./, '$1')
]
[
	({ get [Symbol.toStringTag]() { return 'l' } }).toString().replace(/........(.)./, '$1')
	+ ({ get [Symbol.toStringTag]() { return 'o' } }).toString().replace(/........(.)./, '$1')
	+ ({ get [Symbol.toStringTag]() { return 'g' } }).toString().replace(/........(.)./, '$1')
]
(
	({ get [Symbol.toStringTag]() { return 'l' } }).toString().replace(/........(.)./, '$1')
	+ ({ get [Symbol.toStringTag]() { return 'o' } }).toString().replace(/........(.)./, '$1')
	+ ({ get [Symbol.toStringTag]() { return 'l' } }).toString().replace(/........(.)./, '$1')
)
